INSERT INTO "gem_http_status_codes" VALUES ('400', 'Bad Request');
INSERT INTO "gem_http_status_codes" VALUES ('401', 'Unauthorized');
INSERT INTO "gem_http_status_codes" VALUES ('402', 'Payment Required');
INSERT INTO "gem_http_status_codes" VALUES ('403', 'Forbidden');
INSERT INTO "gem_http_status_codes" VALUES ('404', 'Not Found');
INSERT INTO "gem_http_status_codes" VALUES ('405', 'Method Not Allowed');
INSERT INTO "gem_http_status_codes" VALUES ('406', 'Not Acceptable');
INSERT INTO "gem_http_status_codes" VALUES ('407', 'Proxy Authentication Required');
INSERT INTO "gem_http_status_codes" VALUES ('408', 'Request Timeout');
INSERT INTO "gem_http_status_codes" VALUES ('409', 'Conflict');
INSERT INTO "gem_http_status_codes" VALUES ('410', 'Gone');
INSERT INTO "gem_http_status_codes" VALUES ('411', 'Length Required');
INSERT INTO "gem_http_status_codes" VALUES ('412', 'Precondition Failed');
INSERT INTO "gem_http_status_codes" VALUES ('413', 'Request Entity Too Large');
INSERT INTO "gem_http_status_codes" VALUES ('414', 'Request-URI Too Long');
INSERT INTO "gem_http_status_codes" VALUES ('415', 'Unsupported Media Type');
INSERT INTO "gem_http_status_codes" VALUES ('416', 'Requested Range Not Satisfiable');
INSERT INTO "gem_http_status_codes" VALUES ('417', 'Expectation Failed');
INSERT INTO "gem_http_status_codes" VALUES ('421', 'There are too many connections from your internet address');
INSERT INTO "gem_http_status_codes" VALUES ('422', 'Unprocessable Entity');
INSERT INTO "gem_http_status_codes" VALUES ('423', 'Locked');
INSERT INTO "gem_http_status_codes" VALUES ('424', 'Failed Dependency');
INSERT INTO "gem_http_status_codes" VALUES ('425', 'Unordered Collection');
INSERT INTO "gem_http_status_codes" VALUES ('426', 'Upgrade Required');
INSERT INTO "gem_http_status_codes" VALUES ('449', 'Retry With');
INSERT INTO "gem_http_status_codes" VALUES ('500', 'Internal Server Error');
INSERT INTO "gem_http_status_codes" VALUES ('501', 'Not Implemented');
INSERT INTO "gem_http_status_codes" VALUES ('502', 'Bad Gateway');
INSERT INTO "gem_http_status_codes" VALUES ('503', 'Service Unavailable');
INSERT INTO "gem_http_status_codes" VALUES ('504', 'Gateway Timeout');
INSERT INTO "gem_http_status_codes" VALUES ('505', 'HTTP Version Not Supported');
INSERT INTO "gem_http_status_codes" VALUES ('506', 'Variant Also Negotiates');
INSERT INTO "gem_http_status_codes" VALUES ('507', 'Insufficient Storage');
INSERT INTO "gem_http_status_codes" VALUES ('509', 'Bandwidth Limit Exceeded');
INSERT INTO "gem_http_status_codes" VALUES ('600', 'Unparseable Response Headers');
